### PR TITLE
Change XJC plugin because jaxb2-maven-plugin doesn't work with space into project location

### PR DESCRIPTION
**Pull request by legrosjf**
Signed-off-by: legrosjf <legrosjf@gmail.com>

### CODE REVIEW

**Comment by syllamoh** [comment]
Hi,

I work under Linux OS.
Could you please provide, if possible, the error message with the original plugin ? We use this plugin in many other projects, it'll useful to know if we've been missing something using the plugin.

**Comment by legrosjf** [comment]
> Hi,
> 
> I work under Linux OS.
> Could you please provide, if possible, the error message with the original plugin ? We use this plugin in many other projects, it'll be useful to know if we've been missing something using the plugin.

Hello @syllamoh, I got following message:
[INFO] --- jaxb2-maven-plugin:2.5.0:xjc (xjc) @ core-service ---
[INFO] Created EpisodePath [/home/jeff/Développement/Projets/projets extérieurs/compas/compas-core/core-service/target/generated-sources/jaxb/META-INF/JAXB]: true
[INFO] Ignored given or default xjbSources [/home/jeff/Développement/Projets/projets extérieurs/compas/compas-core/core-service/src/main/xjb], since it is not an existent file or directory.
[INFO] Created EpisodePath [/home/jeff/Développement/Projets/projets extérieurs/compas/compas-core/core-service/target/generated-sources/jaxb/META-INF/JAXB]: true
[ERROR] null [-1,-1] 
org.xml.sax.SAXParseException: schema_reference.4 : Echec de la lecture du document de schéma 'file:/home/jeff/Développement/Projets/projets%20extérieurs/compas/compas-core/home/jeff/Développement/Projets/projets%20extérieurs/compas/compas-core/core-service/src/main/resources/schema/RTE_SCL.xsd' pour les raisons suivantes : 1) Le document est introuvable ; 2) Le document n'a pas pu être lu ; 3) L'élément racine du document n'est pas <xsd:schema>.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException (ErrorHandlerWrapper.java:204)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error (ErrorHandlerWrapper.java:135)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError (XMLErrorReporter.java:396)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError (XMLErrorReporter.java:306)
    at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr (XSDHandler.java:4257)
    at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError (XSDHandler.java:4240)
    at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument1 (XSDHandler.java:2531)
    at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument (XSDHandler.java:2353)
    at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema (XSDHandler.java:575)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema (XMLSchemaLoader.java:617)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar (XMLSchemaLoader.java:576)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar (XMLSchemaLoader.java:542)
    at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema (XMLSchemaFactory.java:276)
    at com.sun.tools.xjc.reader.xmlschema.parser.SchemaConstraintChecker.check (SchemaConstraintChecker.java:81)
    at com.sun.tools.xjc.ModelLoader.loadXMLSchema (ModelLoader.java:301)
    at com.sun.tools.xjc.ModelLoader.load (ModelLoader.java:121)
    at com.sun.tools.xjc.ModelLoader.load (ModelLoader.java:76)
    at com.sun.tools.xjc.Driver.run (Driver.java:324)
    at org.codehaus.mojo.jaxb2.javageneration.AbstractJavaGeneratorMojo.performExecution (AbstractJavaGeneratorMojo.java:475)
    at org.codehaus.mojo.jaxb2.AbstractJaxbMojo.execute (AbstractJaxbMojo.java:337)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.io.FileNotFoundException: /home/jeff/Développement/Projets/projets extérieurs/compas/compas-core/home/jeff/Développement/Projets/projets extérieurs/compas/compas-core/core-service/src/main/resources/schema/RTE_SCL.xsd (Aucun fichier ou dossier de ce type)
    at java.io.FileInputStream.open0 (Native Method)
    at java.io.FileInputStream.open (FileInputStream.java:219)
    at java.io.FileInputStream.<init> (FileInputStream.java:157)
    at java.io.FileInputStream.<init> (FileInputStream.java:112)
    at sun.net.www.protocol.file.FileURLConnection.connect (FileURLConnection.java:86)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream (FileURLConnection.java:184)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity (XMLEntityManager.java:652)
    at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion (XMLVersionDetector.java:150)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse (XML11Configuration.java:860)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse (XML11Configuration.java:824)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse (XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse (AbstractSAXParser.java:1216)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse (SAXParserImpl.java:635)
    at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument (XSDHandler.java:2325)
    at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema (XSDHandler.java:575)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema (XMLSchemaLoader.java:617)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar (XMLSchemaLoader.java:576)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar (XMLSchemaLoader.java:542)
    at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema (XMLSchemaFactory.java:276)
    at com.sun.tools.xjc.reader.xmlschema.parser.SchemaConstraintChecker.check (SchemaConstraintChecker.java:81)
    at com.sun.tools.xjc.ModelLoader.loadXMLSchema (ModelLoader.java:301)
    at com.sun.tools.xjc.ModelLoader.load (ModelLoader.java:121)
    at com.sun.tools.xjc.ModelLoader.load (ModelLoader.java:76)
    at com.sun.tools.xjc.Driver.run (Driver.java:324)
    at org.codehaus.mojo.jaxb2.javageneration.AbstractJavaGeneratorMojo.performExecution (AbstractJavaGeneratorMojo.java:475)
    at org.codehaus.mojo.jaxb2.AbstractJaxbMojo.execute (AbstractJaxbMojo.java:337)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)


I got same exception nine times.

**Comment by Flurb** [comment]
I see spaces in the path: /home/jeff/Développement/Projets/projets extérieurs/compas/compas-core/home/jeff/Développement/Projets/projets extérieurs/compas/compas-core/core-service/src/main/resources/schema/RTE_SCL.xsd. 
In some cases, FileNotFoundException can be caused by spaces in the path. It shouldn't matter, but maybe thats something to try out. Maybe good to exclude this option, because the path itself does exist in the repository.

**Comment by legrosjf** [comment]
Hello @Flurb,
The real path of my project is "/home/jeff/Développement/Projets/projets extérieurs/compas/compas-core" the plugin duplicate it when it try to transform each XSD file.

**Comment by Flurb** [comment]
Yea try it! I don't think that's the problem (I hope not), but it's good to exclude the possibility

**Comment by legrosjf** [comment]
> Yea try it! I don't think that's the problem (I hope not), but it's good to exclude the possibility

I just try to move the project directly into my home and it's working fine.

**Comment by Flurb** [comment]
I'm not sure if I understand.
This Pull Request is purely for adding XJC functionality, so generate Java classes from the src/main/resources/schema directory into the org.lfenergy.compas.scl directory (probably something like src/generated/org/lfenergy/compas/scl directory) with the org.lfenergy.compas.scl package name.

But the title of the Pull Request is making it able to compile under Linux. Why didn't it compile under Linux?

**Comment by Flurb** [comment]
And I think we can use a general schema repository or something, because in the compas-cim-mapping repository we are also using the same XSD schemas (see https://github.com/com-pas/compas-cim-mapping/tree/cim_61850_mapping_mvp/schema/xsd). And of course, we don't like duplicate stuff!

**Review by Flurb — CHANGES_REQUESTED** [review]
See comments in discussion :)

**Comment by syllamoh** [comment]
@legrosjf 
Hi
I see others have already intervened.
I don't think the issue is related to plugins (it is doing correctly its job) or OS. The error is about file not been found. @Flurb pointed out the issue's reason.

**Review by syllamoh — CHANGES_REQUESTED** [review]
I don't think the issue is related to plugins (it is doing correctly its job) or OS. The error is about file not been found as @Flurb pointed out the issue's reason.

**Comment by legrosjf** [comment]
Hello @Flurb ,

My pull request is not to change the behavior, it's just to purpose to change the plugin to another one who are working on my linux configuration. I'm agree to have XSD one times in our project. But first I try to be able to compile, then I will give some modifications.

**Comment by legrosjf** [comment]
I change the title of the pull request to be more related with my situation.

**Review by syllamoh — APPROVED** [review]

**Review by Flurb — APPROVED** [review]

**Comment by syllamoh** [comment]
I know this pull request is closed.

ATTENTION : This plugin may have WARNING issue from JAVA 11+
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:${HOME}.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.0/jaxb-runtime-2.3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

See whether there's a new version that doesn't use reflection

**Pull request merged**
