### PR TITLE
common SCL XSD Handlers implementation

### PR DESCRIPTION
**Pull request by syllamoh**
Signed-off-by: SYLLA MOHAMED <mohamed.sylla@rte-france.com>

### CODE REVIEW

**Comment by Sander3003** [comment]
What stories are covered by this pull-request?
Does this pull-request meet the architecture choices?

**Comment by Flurb** [comment]
And I think it's a good practice to use the same technologies in for each project (for more easy maintenance for example).
So both for example using Maven and Quarkus. :)
In this case, compas-cim-mapping is using Gradle as the build tool, this project is using Maven. And I see this project is using Spring Boot, compas-cim-mapping is using Quarkus. 

It's a good idea to align both! :)

**Comment by syllamoh** [comment]
@Flurb 
Just trying to respect this:  https://github.com/com-pas/contributing/blob/master/CONTRIBUTING.md#basic-maven-usage

**Comment by syllamoh** [comment]
@Sander3003 Hi
It covers a story in compas-sct but codes in this pull-request are abstractions that can be used in the compac-sct to implement the story.

There would be not less that two architectural approaches (in my opinion):
- the XML processing (configuration management - cf. architecture) being done at the front-end (ex. Omicron approach) and the result (workflow management, storage, etc ...) could be handled depending on vendor specification
- the XML processing, mostly delegated to the database (native XML database or database supporting XML technologies - XQUERY, XPATH etc ..), being done at the back-end. That's the approach intended in this pull request and issues related.

Available for discussion about these approaches or any other ones.

Kind regards

**Comment by Flurb** [comment]
I think we have to vote in TSC meeting for used technologies (Quarkus/Spring, Gradle/Maven)

**Comment by syllamoh** [comment]
Software development discussion can't be sold out by vote, but by thorough choices on objectives criteria.
If those criteria are correctly selected with precise knowledge of what is really our needs, the choice would be obvious.

**Comment by Flurb** [comment]
Okay, I do have some other questions:

- This Pull Request covers marshalling/unmarshalling xml files to SCL objects and DAOs for saving XML to databases, correct?
-  Why did we choose PostgreSQL as default in this Pull Request? (I do also see a No-SQL DAO interface, but I see PostgreSQL as default)
- Can the RTE SCL Header be used for general purposes?

Overall, it looks very good! But I don't know how to handle the Spring Boot vs Quarkus discussion yet. I thought we are going to do something with voting, but I'm not sure. But overall it looks like good functionality which we do need!

**Comment by syllamoh** [comment]
@Flurb 
Theere are some codes in this pull request that are not meant to be in the Compas-Core. Some would be moved to Compas-Sct. Only the XSD handler and related subject will remain in the Compas-Core for the moment. After then, progressively, if part of some project code is qualified as commonly useful, that part could be added to the core.

No, PostGreSql is not the default. As the codes are full of Interface and Abstract class. I created some test classes called DefaultXXX to test methods. No DB (SQL or NoSql) would be default. Everything will be configurable.

I'll add in the architecture document the technical structure of the Compas-SCT (All abstraction/interface for handling different type of DB) independently from language or framewok etc ... so it could suitable for any choice that would be made (at least that will the goal)

**Comment by Sander3003** [comment]
@syllamoh It would be great if you can add some technical CoMPAS architecture to prevent confusion in the future.

**Comment by Flurb** [comment]
> @Flurb
> Theere are some codes in this pull request that are not meant to be in the Compas-Core. Some would be moved to Compas-Sct. Only the XSD handler and related subject will remain in the Compas-Core for the moment. After then, progressively, if part of some project code is qualified as commonly useful, that part could be added to the core.
> 
> No, PostGreSql is not the default. As the codes are full of Interfaces and Abstract classes. I created some test classes called DefaultXXX to test methods. No DB (SQL or NoSql) would be default. Everything will be configurable.
> 
> I'll add in the architecture document the technical structure of the Compas-SCT (All abstraction/interface for handling different type of DB) independently from language or framewok etc ... so it could suitable for any choice that would be made (at least that will the goal)

What is the specific functionality that needs to be removed?

**Comment by Sander3003** [comment]
"@Flurb Software development discussion can't be sold out by vote, but by thorough choices on objective criterias.
If those criterias are correctly selected with precise knowledge of what is really our needs, the choice would be obvious."

I'm open for other suggestions to solve this community difference. The possibility of a TSC vote was suggested by Benoit JEANSON . I think it is imported to fix this issue quickly to speed up the development and prevent technical difficulties. @Flurb put a lot of time in comparison the frameworks to be objective: https://com-pas.github.io/compas-architecture/TECHNOLOGY_SURVEY.html

**Review by Flurb — COMMENTED** [review]
Looks great, can we just use the XSD's from IEC-61850-6 without copyright notice or link to an end-user license agreement or something? (like OpenSCD did in their README https://github.com/openscd/open-scd). Did you guys investigate this?

**Comment by legrosjf** [comment]
> Looks great, can we just use the XSD's from IEC-61850-6 without copyright notice or link to an end-user license agreement or something? (like OpenSCD did in their README https://github.com/openscd/open-scd). Did you guys investigate this?

The standard purpose on their site to download a zip file with a link to their license. I think that we should add a reference like openscd project. Moreover, it could be great to directly download XSD files from the standard page. I do it for my own project. If everybody is ok, I could merge my code.

**Comment by syllamoh** [comment]
@Flurb 
I can remove the copyright, that's not a problem. 
But last time we talk about this, no final decision was taken on how to handle this.
If I'm not mistaken, in CIM project you updated the latest version with the same XSD containing copyright.

Again the code is configurable, one can point to a schema path of choice.

Plus, this a incremental development if there's a final decision on what should be done, an issue could be opened and processed.
Also any accepted proposition or evolution should be addressed by opening issue.

If there's any flaws in the code (this pull request) or none respect of coding rules in terms of quality and security or any rule of the compas project development, I'm opened to get feedback.

This code is used in my next pull request for Compas-SCT.

**Review by Flurb — COMMENTED** [review]
Looks good!
Where did you get the XSD schemas btw?

When this is merged, compas-cim-mapping can use this functionality instead :)

**Comment by syllamoh** [comment]
> Looks good!
> Where did you get the XSD schemas btw?
> 
> When this is merged, compas-cim-mapping can use this functionality instead :)

Hi 
From the official. I might not be the last one, I can't tell. But that's not a problem as the XSD will have new version. 
Plus any compas maintainer  can update the schema.

The code can't be merged as it is pending waiting approval.

**Comment by Flurb** [comment]
I know, I didn't approve yet haha.
No I was wondering where you guys downloaded it, because it's different compared to the ones I downloaded :)

**Comment by syllamoh** [comment]
> I know, I didn't approve yet haha.
> No I was wondering where you guys downloaded it, because it's different compared to the ones I downloaded :)

if yours seem to be more up to date, you can open an issue to update the schema

**Review by Flurb — APPROVED** [review]

**Comment by Flurb** [comment]
I see it's being merged into master, but for compas-sct the pull request is merging into develop?
I thought we discussed Git Flow is not fully required, but I think a Develop branch does have play in our case. If so, the init-core-service should be merged into Develop instead of Master

**Comment by syllamoh** [comment]
Hi @Flurb ,

**init-core-service (its initial version) was already merged to develop. (February)**
The review is analyzing and insuring that there's no flaws in the code (this pull request) and full respect of coding rules in terms of quality and security and all rule of the compas project development are met. These are the only condition/criteria for approval. **The pull request should be rejected otherwise.**

Reviewer enhancement's proposal should not be a condition/criteria for approval/non approval if it's not related to the pull request. Those should be addressed in issues. Unfortunately that how reviewers proceed here.
**This pull request been here since the beginning of February.** There even been some enhancement (@legrosjf pull request) on the develop branch.
Instead of feedback on flaws in the code or full respect of coding rules in terms of quality and security or all rules of the compas project development been met, discussion was focused on unrelated subject and other enhancement. Hence the difference between branches.

It's urgent we try to organize the way pull request are addressed. Let make difference between what is to be done for the pull request and what is a potential issue (enhancement) to opened.

**Comment by legrosjf** [comment]
We should not remove copyright notice from XSD files (cf "https://www.iec.ch/webstore/custserv/pdf/CC-EULA.pdf" document). We should also add the disclamer defined into this document. For a library, we could put it into the README.md document but for software like SCT or CIM-mapping, this should be displayed into the software.

**Comment by syllamoh** [comment]
Hi @legrosjf 

Agree.

However, isn't better to open issue for updating the README.md with the solution suggested ?

One asking to remove copyright or/and update README.md and other saying keep the copyright, I think that is out of the scope of the pull request. And Keep evolving the pull request code is very bad idea (I'm the first to blame).
I recall:

> The review should be analyzing and insuring that there's no flaws in the code (of the pull request) and full respect of coding rules in terms of quality and security and all rule of the compas project development are met. These should be the only condition/criteria for approval. The pull request should be rejected otherwise.

**Comment by Flurb** [comment]
XSD schemas need to be removed.
These XSD schemas will be hosted in https://github.com/com-pas/compas-scl-xsd

**Comment by syllamoh** [comment]
@Flurb 
Not in this pull request!

**Comment by Flurb** [comment]
I didn't see the XSD schemas were already added to the develop branch.
So for the XSD schemas it's fine!

**Review by Flurb — CHANGES_REQUESTED** [review]
We can't merge this, because it's a merge into the Master branch.

According to the Gitflow (which we are using), the Master branch cannot be merged directly into (except from a Release Branch or Hotfix branch).
I can imagine if we're saying Release branches aren't useful for us, that we ignore them and merge from Develop directly into Master and create Release tags instead of using Release branches.

This feature branch is merged directly into the master branch, which is definitely not the way to go. Master branches should only contain already released code and should always have a "deployable state".

**Comment by syllamoh** [comment]
@Flurb 

If that's rule OK for me. But it should be written some where, because I don't see that rule anywhere.

This is a good example why in some circumstance you need default branch different from master. This answer to you question, why I use the "develop branch" in compas-sct and compas-core. Even the benefit goes beyond this specific example.

**Comment by Flurb** [comment]
> @Flurb
> 
> If that's rule OK for me. But it should be written some where, because I don't see that rule anywhere.
> 
> This is a good example why in some circumstance you need default branch different from master. This answer to you question, why I use the "develop branch" in compas-sct and compas-core. Even the benefit goes beyond this specific example.

Agree! We can talk about it in the next Community Call today!

**Pull request closed without merging**
